### ISSUE TITLE
What is “Entity Path”?

### ISSUE THREAD

**Issue by apjanke** [paolosalvatori/ServiceBusExplorer#323]
In the Connect dialog variants with multiple fields for creating the connection, there's an “Entity Path” field. What is this, and how can I use it correctly? I've tried a couple things, and no matter what, I get exceptions in the log.

Based on the [.NET SessionClient.EntityPath documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.sessionclient.entitypath?view=azure-dotnet), I'm guessing that it's supposed to be a Queue, Topic, or Subscription name/path. But none of those behaves well when I use them here.

I have an ASB Namespace mrtl-rma-test-01 with one Queue “rma-pricing-requests” and one Topic “rma-pricing-notifications”.

Starting from here:

![bpihlddmikmlejdh](https://user-images.githubusercontent.com/2618447/54361323-2d642d00-463d-11e9-962c-600d26eda786.png)

If I put in the queue name “rma-pricing-requests” as the Entity Path, then the connection succeeds, and the navigation tree contains Topics, Event Hubs, and Relays nodes, but they're all empty, and there is no actual topic node under Topics. The following error messages appear in the log:

```
<09:31:22> The files C:\Users\NY510094\AppData\Roaming\Service Bus Explorer\UserSettings.config and C:\ProgramData\chocolatey\lib\ServiceBusExplorer\tools\ServiceBusExplorer.exe.Config are used for the configuration settings.
<09:31:37> The application is now connected to the sb://mrtl-rma-test-01.servicebus.windows.net/ service bus namespace.
<09:31:37> MessagingFactory successfully created
<09:31:39> The queue rma-pricing-requests has been successfully retrieved.
<09:31:39> Failed to retrieve Notification Hub entities. Exception: System.UnauthorizedAccessException: The remote server returned an error: (401) Unauthorized. claim is empty. TrackingId:2b57b8bf-5da5-4dae-ab4a-ea4097c92f57_G12, SystemTracker:mrtl-rma-test-01.servicebus.windows.net:$Resources/NotificationHubs, Timestamp:2019-03-14T13:31:38 ---> System.Net.WebException: The remote server returned an error: (401) Unauthorized.
              at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
              at Microsoft.Azure.NotificationHubs.Messaging.ServiceBusResourceOperations.GetAllAsyncResult.<GetAsyncSteps>b__81(GetAllAsyncResult thisPtr, IAsyncResult r)
              at Microsoft.Azure.NotificationHubs.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
              --- End of inner exception stack trace ---

           Server stack trace:


           Exception rethrown at [0]:
              at Microsoft.Azure.NotificationHubs.Common.ExceptionDispatcher.Throw(Exception exception)
              at Microsoft.Azure.NotificationHubs.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
              at Microsoft.Azure.NotificationHubs.NamespaceManager.EndGetNotificationHubs(IAsyncResult result)
              at Microsoft.Azure.ServiceBusExplorer.Forms.MainForm.GetEntities(EntityType entityType) in C:\projects\servicebusexplorer\src\ServiceBusExplorer\Forms\MainForm.cs:line 4362
<09:31:39> Failed to retrieve Service Bus topics. Exception: Microsoft.ServiceBus.Messaging.MessagingException: Cannot get entity 'rma-pricing-requests' because it is not of type TopicDescription. Check that you are using method(s) with the correct entity type. ---> System.Runtime.Serialization.SerializationException: Error in line 1 position 2655. Expecting element 'TopicDescription' from namespace 'http://schemas.microsoft.com/netservices/2010/10/servicebus/connect'.. Encountered 'None'  with name '', namespace ''.
              at System.Runtime.Serialization.DataContractSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
              at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
              at Microsoft.ServiceBus.Messaging.MessagingDescriptionSerializer`1.DeserializeFromAtomFeed(Stream stream)
              at Microsoft.ServiceBus.Messaging.ServiceBusResourceOperations.GetAsyncResult`1.<GetAsyncSteps>d__22.MoveNext()
              --- End of inner exception stack trace ---
              at Microsoft.Azure.ServiceBusExplorer.ServiceBusHelper.GetTopicUsingEntityPath() in C:\projects\servicebusexplorer\src\ServiceBusExplorer\Helpers\ServiceBusHelper.cs:line 2087
              at Microsoft.Azure.ServiceBusExplorer.ServiceBusHelper.GetTopics(String filter) in C:\projects\servicebusexplorer\src\ServiceBusExplorer\Helpers\ServiceBusHelper.cs:line 2062
              at Microsoft.Azure.ServiceBusExplorer.Forms.MainForm.GetEntities(EntityType entityType) in C:\projects\servicebusexplorer\src\ServiceBusExplorer\Forms\MainForm.cs:line 4477
```

If I put in the Topic name “rma-pricing-notifications” as the Entity Path, the connection succeeds, and Topics, Event Hubs, and Relays nodes appear, and there is an "rma-pricing-notifications" node under Topics. But I still get errors in the log:

```
<09:29:28> The files C:\Users\NY510094\AppData\Roaming\Service Bus Explorer\UserSettings.config and C:\ProgramData\chocolatey\lib\ServiceBusExplorer\tools\ServiceBusExplorer.exe.Config are used for the configuration settings.
<09:29:51> The application is now connected to the sb://mrtl-rma-test-01.servicebus.windows.net/ service bus namespace.
<09:29:51> MessagingFactory successfully created
<09:29:53> The topic rma-pricing-notifications has been successfully retrieved.
<09:29:53> The subscription azr-linux-64923-20190313-145748 for the rma-pricing-notifications topic has been successfully retrieved.
<09:29:53> Failed to retrieve Notification Hub entities. Exception: System.UnauthorizedAccessException: The remote server returned an error: (401) Unauthorized. claim is empty. TrackingId:4ce35713-b490-43ef-b98f-f67e27f61a03_G22, SystemTracker:mrtl-rma-test-01.servicebus.windows.net:$Resources/NotificationHubs, Timestamp:2019-03-14T13:29:52 ---> System.Net.WebException: The remote server returned an error: (401) Unauthorized.
              at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
              at Microsoft.Azure.NotificationHubs.Messaging.ServiceBusResourceOperations.GetAllAsyncResult.<GetAsyncSteps>b__81(GetAllAsyncResult thisPtr, IAsyncResult r)
              at Microsoft.Azure.NotificationHubs.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

              --- End of inner exception stack trace ---


           Server stack trace:

          

           Exception rethrown at [0]:
              at Microsoft.Azure.NotificationHubs.Common.ExceptionDispatcher.Throw(Exception exception)
              at Microsoft.Azure.NotificationHubs.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
              at Microsoft.Azure.NotificationHubs.NamespaceManager.EndGetNotificationHubs(IAsyncResult result)
              at Microsoft.Azure.ServiceBusExplorer.Forms.MainForm.GetEntities(EntityType entityType) in C:\projects\servicebusexplorer\src\ServiceBusExplorer\Forms\MainForm.cs:line 4362
<09:29:53> Failed to retrieve Service Bus queues. Exception: Microsoft.ServiceBus.Messaging.MessagingException: Cannot get entity 'rma-pricing-notifications' because it is not of type QueueDescription. Check that you are using method(s) with the correct entity type. ---> System.Runtime.Serialization.SerializationException: Error in line 1 position 2117. Expecting element 'QueueDescription' from namespace 'http://schemas.microsoft.com/netservices/2010/10/servicebus/connect'.. Encountered 'None'  with name '', namespace ''.
              at System.Runtime.Serialization.DataContractSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
              at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
              at Microsoft.ServiceBus.Messaging.MessagingDescriptionSerializer`1.DeserializeFromAtomFeed(Stream stream)
              at Microsoft.ServiceBus.Messaging.ServiceBusResourceOperations.GetAsyncResult`1.<GetAsyncSteps>d__22.MoveNext()
              --- End of inner exception stack trace ---
              at Microsoft.Azure.ServiceBusExplorer.ServiceBusHelper.GetQueueUsingEntityPath() in C:\projects\servicebusexplorer\src\ServiceBusExplorer\Helpers\ServiceBusHelper.cs:line 1932
              at Microsoft.Azure.ServiceBusExplorer.ServiceBusHelper.GetQueues(String filter) in C:\projects\servicebusexplorer\src\ServiceBusExplorer\Helpers\ServiceBusHelper.cs:line 1907
              at Microsoft.Azure.ServiceBusExplorer.Forms.MainForm.GetEntities(EntityType entityType) in C:\projects\servicebusexplorer\src\ServiceBusExplorer\Forms\MainForm.cs:line 4441
```

Am I using this right?

Maybe Entity Path could have a tooltip explaining what it is, since this doesn't seem to be a term commonly used in the ASB documentation?

**Comment by paolosalvatori** [comment]
Hi @apjanke 

The EntityPath should work as expected, that is, as you noticed above it represents the path of the messaging entity, or, if you prefer, its name. Here is an example: let's say I want to select only the orders queue in my namespace which contains tens or hundreds of entities. I can create a filter as shown in the following picture:
![Ashampoo_Snap_martedì 11 giugno 2019_11h32m55s_001_](https://user-images.githubusercontent.com/1658419/59261456-cc4cf500-8c3d-11e9-9d28-970c6dfe65d6.png)

Note: in you case the error was due to the fact that the tool failed to retrieve notification hubs from the namespace. At the beginning, event hubs, notification hubs, relays and service bus queues and topics were all in the same namespace. Then the product group decided to create separate kinds of namespace kind for each entity type. The problem is that the connection string does not provide any clue on the kind of entities of the namespace. So the tool tries to retrieve all kind of entities and should mask the exception. I don't know why you got an exception. Said that, the connect form allows you to explicitly select the entities that you want to retrieve. Hope this helps!
