### ISSUE TITLE
Feature Request: Option to configure timeout

### ISSUE THREAD

**Issue by gldraphael** [paolosalvatori/ServiceBusExplorer#485]
I'm haven't been able to connect to any of my namespaces in the East US region since yesterday. They timeout. It has always worked until now. (Other regions work fine.) 

Would be nice if we had an option to configure the timeout duration in some sort of global settings.

```
<09:58:13> MessagingFactory successfully created
<09:58:26> Failed to retrieve Service Bus queues. Exception: System.TimeoutException: The operation has timed out.
              at Microsoft.Azure.ServiceBusExplorer.ServiceBusHelper.GetQueues(String filter) in C:\projects\servicebusexplorer\src\ServiceBusExplorer\Helpers\ServiceBusHelper.cs:line 1901
              at Microsoft.Azure.ServiceBusExplorer.Forms.MainForm.GetEntities(EntityType entityType) in C:\projects\servicebusexplorer\src\ServiceBusExplorer\Forms\MainForm.cs:line 4441
<09:58:26> Failed to retrieve Service Bus topics. Exception: System.TimeoutException: The operation has timed out.
              at Microsoft.Azure.ServiceBusExplorer.ServiceBusHelper.GetTopics(String filter) in C:\projects\servicebusexplorer\src\ServiceBusExplorer\Helpers\ServiceBusHelper.cs:line 2056
              at Microsoft.Azure.ServiceBusExplorer.Forms.MainForm.GetEntities(EntityType entityType) in C:\projects\servicebusexplorer\src\ServiceBusExplorer\Forms\MainForm.cs:line 4477
```

**Comment by SeanFeldman** [comment]
Have you tried this?
![image](https://user-images.githubusercontent.com/1309622/102854170-358af800-43df-11eb-807f-3f63aafc48be.png)

**Comment by gldraphael** [comment]
View => Options?

No I dint even open that dialog.. I assumed it was to configure view options.

I'm able to connect to the East US namespaces now without any problems, but I think the options in that dialog should be enough. Thanks!
