### ISSUE TITLE
Cannot connect to an Event Hub with only Listen claim

### ISSUE THREAD

**Issue by changov** [paolosalvatori/ServiceBusExplorer#718]
I'm providing a connection string from an EH _shared access policy_ that allows only Listen permission/claim. This is the connection error: "**Manage,EntityRead claims required for this operation**"

```
<20:33:04> The application is now connected to the sb://xxxx.servicebus.windows.net/ service bus namespace.
<20:33:04> MessagingFactory successfully created.
<20:33:04> Failed to retrieve EventHub entities. Exception: System.UnauthorizedAccessException: The remote server returned an error: (401) Unauthorized. claim is empty or token is invalid. TrackingId:70d90e81-30e0-4b77-a748-68584d47d64c_G9S2, SystemTracker:xxxx.servicebus.windows.net:$Resources/EventHubs, Timestamp:2023-04-09T03:33:04 ---> System.Net.WebException: The remote server returned an error: (401) Unauthorized.

              at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)

              at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

<20:33:05> Failed to retrieve Service Bus queues. Exception: System.UnauthorizedAccessException: The remote server returned an error: (401) Unauthorized. Manage,EntityRead claims required for this operation. TrackingId:a34e32c3-9b08-43bf-909c-a38462af1855_G9S2, SystemTracker:xxxx.servicebus.windows.net:insights-logs-partitionkeystatistics, Timestamp:2023-04-09T03:33:05 ---> System.Net.WebException: The remote server returned an error: (401) Unauthorized.

```

**Comment by soychrisdev** [comment]
I have the same issue with my EH, can be an error about of EH updated SAS policies?

**Comment by NaorisKong** [comment]
I think it can`t be implementation, because you need Manage claim to read entities.

> <11:44:13> Failed to retrieve EventHub entities. Exception: System.UnauthorizedAccessException: The remote server returned an error: (401) Unauthorized. Manage,EntityRead claims required for this operation. TrackingId:343ad4b6-a69c-4f77-a8f6-db4f800b3e24_G23, SystemTracker:sbetest.servicebus.windows.net:$Resources/EventHubs, Timestamp:2024-11-08T03:44:12 ---> System.Net.WebException: The remote server returned an error: (401) Unauthorized.
