### ISSUE TITLE
Service bus explorer not working for IOThub internal event hub.

### ISSUE THREAD

**Issue by gudipudipradeep** [paolosalvatori/ServiceBusExplorer#759]
```python
<14:41:07> The file C:\ServiceBusExplorer-5.0.18\ServiceBusExplorer.exe.Config is used for the configuration settings.
<14:41:27> The application is now connected to the sb://iothub-ns-opintel-ev-3347978-147277144e.servicebus.windows.net/ service bus namespace.
<14:41:27> MessagingFactory successfully created.
<14:42:08> Failed to retrieve EventHub entities. Exception: Microsoft.ServiceBus.Messaging.MessagingException: The underlying connection was closed: An unexpected error occurred on a send. TrackingId:048a872f-af34-49d1-b993-1ff74b4209e7, SystemTracker:iothub-ns-opintel-ev-3347978-147277144e.servicebus.windows.net, Timestamp:2023-12-20T09:12:08 ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host

              at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)

              at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)

              --- End of inner exception stack trace ---

              at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)

              at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)

              --- End of inner exception stack trace ---

              at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)

              at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

           --- End of stack trace from previous location where exception was thrown ---

              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

              at Microsoft.ServiceBus.Messaging.ServiceBusResourceOperations.GetAllTask.<OnRunAsync>d__17.MoveNext()

              --- End of inner exception stack trace ---

              at Microsoft.ServiceBus.Messaging.ServiceBusResourceOperations.GetAllTask.<OnRunAsync>d__17.MoveNext()

           --- End of stack trace from previous location where exception was thrown ---

              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

              at Microsoft.ServiceBus.Messaging.ServiceBusResourceOperations.RetryResourceTask`1.<RunAsync>d__34.MoveNext()

           --- End of stack trace from previous location where exception was thrown ---

              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

              at Microsoft.ServiceBus.NamespaceManager.<GetEventHubsAsync>d__75.MoveNext()

           --- End of stack trace from previous location where exception was thrown ---

              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

              at ServiceBusExplorer.Forms.MainForm.<ShowEntities>d__320.MoveNext() in D:\a\ServiceBusExplorer\ServiceBusExplorer\src\ServiceBusExplorer\Forms\MainForm.cs:line 4263
<14:42:09> The application is now connected to the sb://iothub-ns-opintel-ev-3347978-147277144e.servicebus.windows.net/ service bus namespace.
<14:42:09> MessagingFactory successfully created.

```

**Comment by ErikMogensen** [comment]
@gudipudipradeep, is there any difference between an IOThub internal event hub and a "normal" Azure Event hub?

**Comment by ErikMogensen** [comment]
Closing due to inactivity
